# Generated by cucumber-sinatra. (2012-08-17 16:20:57 -0500)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/srna.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = SRNA

class SRNAWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  SRNAWorld.new
end
